version: '1.0.42'

services:
  jupyterhub_lab_container:
    image: jupyterhub_lab:1.0
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8088:80"
    volumes:
      - home-volume:/home

volumes:
  home-volume:
